package randomstring

import (
	"crypto/rand"
	"encoding/base64"
)

// TokenBytes - default token bytes
const TokenBytes = 32

// RandomString interface
type RandomString interface {
	GenerateToken() (string, error)
	NumberOfBytes(base64String string) (int, error)
}

type randomString struct{}

// NewRandomString instantiates RandomString
func NewRandomString() RandomString {
	return &randomString{}
}

// Generate token of a predetermined byte size.
// Generate a byte slice of size nBytes and then
// return a string that is the base64 URL encoded version
// of that byte slice
func (rd *randomString) GenerateToken() (string, error) {
	b, err := rd.generateRandomBytes(TokenBytes)
	if err != nil {
		return "", err
	}
	return base64.URLEncoding.EncodeToString(b), nil
}

// Generate n random bytes.
func (rd *randomString) generateRandomBytes(n int) ([]byte, error) {
	b := make([]byte, n)
	_, err := rand.Read(b)
	if err != nil {
		return nil, err
	}
	return b, nil
}

// Returns the number of bytes used in any string
// generated by the String or GenerateToken function
func (rd *randomString) NumberOfBytes(base64String string) (int, error) {
	b, err := base64.URLEncoding.DecodeString(base64String)
	if err != nil {
		return -1, err
	}
	return len(b), nil
}
