CREATE USER dev_user WITH PASSWORD '123test';
ALTER USER dev_user WITH SUPERUSER;
ALTER ROLE dev_user CREATEROLE CREATEDB;

CREATE DATABASE base_dev;
GRANT ALL PRIVILEGES ON DATABASE base_dev to dev_user;